name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and publish an image
      uses: elgohr/Publish-Docker-Github-Action@v5

      with:
        name: brighteyed/yttg/yttg
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}    
        registry: docker.pkg.github.com
